### ISSUE TITLE
cannot get public key for key exchange

### ISSUE THREAD

**Issue by wamserma** [jetperch/pymonocypher#1]
pymonocypher exposes only a single function to obtain a public key, which maps to getting the public key for signatures. This key is different from the key required to do key exchange. (So pymonocypher is not compatible with e.g. plain monocypher here.)
from https://monocypher.org/manual/sign
> The public keys are different, [...].
Pymonocypher should provide both functions and also replicate the warning about using keypairs only for signing or (exclusively) for key exchange from the Monocypher Manual in in the function descriptions.

See 
https://github.com/jetperch/pymonocypher/compare/master...wamserma:263755d

for an example how both functions could be exposed. The example deliberately breaks the existing API to make users aware of the different public keys.
You may freely copy & paste from https://github.com/wamserma/pymonocypher/commit/263755d5915b6845059e6741730b1e8216f7be90.

**Comment by yota-code** [comment]
Indeed, something is missing here :) no other function for public key derivation is exposed (generate_key_pair() uses public_key_compute()) and this example fails :
```
# key exchange
# ALICE
a_private_secret, a_public_secret = monocypher.generate_key_pair()

# BOB
b_private_secret, b_public_secret = monocypher.generate_key_pair()

b_shared_secret = monocypher.key_exchange(b_private_secret, a_public_secret)
a_shared_secret = monocypher.key_exchange(a_private_secret, b_public_secret)

print(b_shared_secret)
print(a_shared_secret)
```

**Comment by yota-code** [comment]
Thank you @wamserma ... perfect patch :)

```
# key exchange
# ALICE
a_private_secret, a_public_secret = monocypher.generate_exchange_key_pair()

# BOB
b_private_secret, b_public_secret = monocypher.generate_exchange_key_pair()

b_shared_secret = monocypher.key_exchange(b_private_secret, a_public_secret)
a_shared_secret = monocypher.key_exchange(a_private_secret, b_public_secret)

print(b_shared_secret)
print(a_shared_secret)
```

works as intended

**Comment by mliberty1** [comment]
Thank you @wamserma and @yota-code!  I incorporated this change into 0.1.3.  However, I used function names compute_signing_public_key and compute_key_exchange_public_key to be parallel with generate_signing_key_pair and generate_key_exchange_key_pair.  I also added a unit test with @yota-code's example.

Sorry for taking so long to upstream this!  This issue was opened during my [Joulescope](https://www.joulescope.com/) campaign, and I forgot.  Thanks for the reminder @yota-code!
