### ISSUE TITLE
compute_signing_public_key returning empty key

### ISSUE THREAD

**Issue by tridge** [jetperch/pymonocypher#9]
We've recently updated to pymonocypher 4.0.2.1 from pypi. 
With python 3.10 I get an empty public key from this script:
```
#!/usr/bin/env python3
'''
generate a public/private key pair using Monocypher
'''

import sys
import base64
import monocypher

private_key = monocypher.generate_key()
print("got private_key: len=%u" % len(private_key))
public_key = monocypher.compute_signing_public_key(private_key)
print("got public_key: len=%u" % len(public_key))

if len(public_key) == 0:
    print("ERROR: zero length public key")
```

If I downgrade to pymonocypher 3.1.3.2 (the previous release) it works fine

**Comment by mliberty1** [comment]
Monocypher removed the unsafe signature API in 4.0.0 [[changelog](https://monocypher.org/changelog)].  While `generate_key` generates a random 32-byte key, it no longer generates a signing key pair.  You should use `generate_signing_key_pair` instead.

```
def generate_signing_key_pair():
    """Generate a new keypair for signing using default settings.

    :return (secret, public).

    To print a key, use the following code snippet:

        import binascii
        print(binascii.hexlify(key))
    """
    secret = bytes(64)
    public = bytes(32)
    crypto_eddsa_key_pair(secret, public, generate_key())
    return secret, public
```

We should modify `compute_signing_public_key`.  It now requires the 64-byte secret key, not a plain 32-byte key as documented.  It should throw an exception if you pass a legacy 32-byte secret key.

**Comment by mliberty1** [comment]
4.0.2.2 with throw a `ValueError` for this case.  I also updated the doc strings to help.
